// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7lIzhPkMz0DilUFxG_TEKHpGlmItyBs',
    appId: '1:155483655749:web:a54ce0038e4ff575ca9d2c',
    messagingSenderId: '155483655749',
    projectId: 'harvest-valley-ti4',
    authDomain: 'harvest-valley-ti4.firebaseapp.com',
    storageBucket: 'harvest-valley-ti4.firebasestorage.app',
    measurementId: 'G-TZ7Q2JYJCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqX-nJAmGtjOn3I-42DeW00ccnst3Yspw',
    appId: '1:155483655749:android:046ffc92f60d0810ca9d2c',
    messagingSenderId: '155483655749',
    projectId: 'harvest-valley-ti4',
    storageBucket: 'harvest-valley-ti4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOgryMcYKgmqDstD8lxnnQDgmwmFM2sQ',
    appId: '1:155483655749:ios:7c66cb3c85cc8e48ca9d2c',
    messagingSenderId: '155483655749',
    projectId: 'harvest-valley-ti4',
    storageBucket: 'harvest-valley-ti4.firebasestorage.app',
    iosBundleId: 'com.example.harvestValley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOgryMcYKgmqDstD8lxnnQDgmwmFM2sQ',
    appId: '1:155483655749:ios:7c66cb3c85cc8e48ca9d2c',
    messagingSenderId: '155483655749',
    projectId: 'harvest-valley-ti4',
    storageBucket: 'harvest-valley-ti4.firebasestorage.app',
    iosBundleId: 'com.example.harvestValley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN7lIzhPkMz0DilUFxG_TEKHpGlmItyBs',
    appId: '1:155483655749:web:85c58d04d193a14eca9d2c',
    messagingSenderId: '155483655749',
    projectId: 'harvest-valley-ti4',
    authDomain: 'harvest-valley-ti4.firebaseapp.com',
    storageBucket: 'harvest-valley-ti4.firebasestorage.app',
    measurementId: 'G-0RKJ34GYZZ',
  );

}